"use client";

import { useEffect, useState } from "react";
import { ArrowDownRight, Terminal, Zap, ChevronDown } from "lucide-react";

const stats = [["01","COMPETITION","2 ROUNDS"],["02","DURATION","03 HOURS"],["03","LANGUAGES","ANY"],["04","PLATFORM","CUSTOM"]];
const faqs = [["Who can participate?","Event eligibility details will be announced by Team Parsec."],["How many rounds are there?","Bithunt consists of two competitive rounds."],["How long is the competition?","The competition runs for three hours."],["Which programming languages can I use?","Any programming language supported by the custom platform can be used."]];

export default function Home(){
 const [open,setOpen]=useState<number|null>(null); const [boot,setBoot]=useState(true);
 useEffect(()=>{const t=setTimeout(()=>setBoot(false),850);return()=>clearTimeout(t)},[]);
 return <main className={boot?"site booting":"site"}><div className="scanlines"/><div className="noise"/>
 <header className="topbar"><a className="brand" href="#top"><span>BITHUNT</span><i>//</i><small>PARSEC</small></a><nav><a href="#about">ABOUT</a><a href="#hunt">THE HUNT</a><a href="#rules">RULES</a><a href="#faq">FAQ</a></nav><a className="mini-cta" href="#register">REGISTER <ArrowDownRight size={15}/></a></header>
 <section id="top" className="hero"><div className="hero-grid"/><div className="hero-copy"><div className="eyebrow"><span className="live-dot"/> SYSTEM STATUS: <b>AWAITING HUNTERS</b></div><p className="kicker">TEAM PARSEC // IIT DHARWAD</p><h1><span>BIT</span><em>HUNT</em></h1><div className="hero-line"><span>01</span><div/><span>CODE / THINK / HUNT</span></div><p className="hero-text">A competitive programming challenge built to test <strong>problem-solving, data structures and algorithms.</strong></p><div className="hero-actions"><a className="cyber-button primary" href="#register">ENTER THE HUNT <ArrowDownRight size={18}/></a><a className="cyber-button" href="#about">EXPLORE EVENT</a></div></div><div className="terminal-card"><div className="terminal-head"><span>root@bithunt:~</span><span>● ● ●</span></div><div className="terminal-body"><p><b>$</b> initialize_bithunt</p><p className="ok">[OK] EVENT CORE ONLINE</p><p><b>$</b> scan --competition</p><p>rounds: <span>02</span></p><p>duration: <span>03h</span></p><p>languages: <span>ANY</span></p><p><b>$</b> status</p><p className="warning">REGISTRATION: <span>TBA</span></p><div className="cursor">█</div></div></div><div className="scroll-hint"><span>SCROLL TO HUNT</span><ArrowDownRight size={16}/></div></section>
 <section id="about" className="section"><div className="section-index">01 / ABOUT</div><div className="section-heading"><p>THE OBJECTIVE</p><h2>THINK DIFFERENT.<br/><span>CODE SMARTER.</span></h2></div><div className="about-grid"><p className="lead">Bithunt is a coding competition where your <span>logic</span>, <span>algorithmic thinking</span>, and ability to solve under pressure become your biggest weapons.</p><div className="quote-box"><Terminal size={18}/><p>&gt; Find the problem.<br/>&gt; Find the pattern.<br/>&gt; Find the solution.</p></div></div></section>
 <section id="hunt" className="section hunt"><div className="section-index">02 / THE HUNT</div><div className="section-heading"><p>COMPETITION PROTOCOL</p><h2>THE HUNT<br/><span>BEGINS HERE.</span></h2></div><div className="stat-grid">{stats.map(([n,label,value])=><div className="stat" key={n}><small>{n}</small><p>{label}</p><strong>{value}</strong><Zap size={15}/></div>)}</div><div className="rounds"><article><span>ROUND 01</span><h3>THE SEARCH</h3><p>Enter the arena. Decode the problems. Build the fastest path to a solution.</p></article><div className="round-arrow">→</div><article><span>ROUND 02</span><h3>THE CONQUEST</h3><p>Push your limits, optimize your approach, and climb the final ranking.</p></article></div></section>
 <section id="rules" className="section rules"><div className="section-index">03 / RULES</div><div className="section-heading"><p>MISSION PARAMETERS</p><h2>KNOW THE<br/><span>RULES.</span></h2></div><div className="rule-grid">{["Problem-solving is the mission.","Any programming language.","Maximum team size: 4.","Competition duration: 3 hours."].map((x,i)=><div className="rule" key={x}><span>0{i+1}</span><p>{x}</p></div>)}</div></section>
 <section id="faq" className="section faq"><div className="section-index">04 / FAQ</div><div className="faq-list">{faqs.map(([q,a],i)=><button className={"faq-item "+(open===i?"open":"")} key={q} onClick={()=>setOpen(open===i?null:i)}><span>0{i+1}</span><strong>{q}</strong><ChevronDown size={18}/><p>{a}</p></button>)}</div></section>
 <section id="register" className="register"><div className="register-bg">BITHUNT</div><p>FINAL TRANSMISSION // REGISTRATION</p><h2>READY TO<br/><span>HUNT?</span></h2><a className="cyber-button primary big" href="#top">REGISTRATION LINK — TBA <ArrowDownRight size={20}/></a><small>EVENT DATE: TO BE ANNOUNCED · PRIZES: TO BE ANNOUNCED</small></section>
 <footer><div><b>BITHUNT</b><span>// TEAM PARSEC · IIT DHARWAD</span></div><div>CONTACT: 7666804195</div><div>© 2026 PARSEC</div></footer>
 </main>;
}
